In [5]:
# coding: utf-8
# Name: André Moreira Souza
# NUSP: 9778985
# Course Code: SCC0251
# Semester: 2019/1
# Assignment: 2 - Image enhancement and filtering

In [6]:
import numpy as np
import scipy
import imageio

## Defining functions

In [14]:
A = np.random.rand(250, 250)

In [16]:
print(A)

[[0.85603473 0.21282257 0.20069637 ... 0.1339425  0.8587118  0.90086254]
 [0.19044424 0.26316648 0.14405705 ... 0.64429181 0.44316553 0.05138068]
 [0.45798556 0.54217239 0.34956559 ... 0.02969309 0.75120985 0.07553086]
 ...
 [0.991142   0.0852528  0.66497835 ... 0.31386907 0.9504732  0.255203  ]
 [0.68043129 0.86962507 0.6119429  ... 0.98827641 0.42812499 0.56671893]
 [0.77389912 0.08732065 0.43345363 ... 0.32929193 0.49210121 0.43157931]]


In [24]:
A[:1, :]

array([[0.85603473, 0.21282257]])

In [9]:
# F == 1
def adaptive_denoising(g, gamma, k, mode):
    # calculating estimated dispersion measure disp_h
    # then applying denoising over each pixel
    img_final = np.zeros(g.shape, dtype=np.double)
    if mode == 'average':
        disp_h = np.std(g[:g.shape[0]//6, :g.shape[1]//6])
    elif mode == 'robust':
        disp_h = np.percentile(g[:g.shape[0]//6, :g.shape[1]//6], 25) - np.percentile(g[:g.shape[0]//6, :g.shape[1]//6], 75)
    else raise ValueError("Unexpected value for mode (should be in ['average', 'robust'])")
    

# F == 2
def constrained_least_squares(g, gamma, k, sigma):
    pass

# gaussian_filter function
def gaussian_filter(k=3, sigma=1.0):
    arx = np.arange((-k // 2) + 1.0, (k // 2) + 1.0)
    x, y = np.meshgrid(arx, arx)
    filt = np.exp(-(1/2) * (np.square(x) + np.square(y)) / np.square(sigma))
    return filt / np.sum(filt)

# Normalize value of an numpy array between 0 and a given max value
def normalize (arr, maxvalue):
    return (arr-arr.min()) * (maxvalue / (arr.max()-arr.min()))

# root mean squared error (RMSE) function
def rmse (img_g, img_r):
    np.sqrt((np.sum(np.power(img_g.astype(np.double) - img_r.astype(np.double), 2)))/(img_g.shape[0]*img_g.shape[1]))

## Main function

In [10]:
if __name__ == '__main__':
    # get user input
    fpath, gpath = str(input()).strip(), str(input()).strip() # f = reference image, g = degraded image
    f, g = imageio.imread(fpath), imageio.imread(gpath) # reading images f and g
    F = int(input()) # F = type of filter for restoration (1 -> denoising; 2 -> deblurring)
    if (F not in [1, 2]): raise ValueError("Unexpected value for F (should be '1' or '2')")
        
    gamma = np.double(input())
    if (gamma < 0 or gamma > 1): raise ValueError("Unexpected value for gamma (should be a float between '0' and '1')")
        
    k = int(input()) # k = size of denoising filter or degradation function (k in [3, 5, 7, 9, 11])
    if (k not in [3, 5, 7, 9, 11]): raise ValueError("Unexpected value for k (should be in [3, 5, 7, 9, 11])")
        
    # get specific inputs and restore image g
    if(F == 1):
        mode = str(input())
        if (mode not in ['average', 'robust']): raise ValueError("Unexpected value for mode (should be in ['average', 'robust'])")
        # f_r = F1
    elif (F == 2):
        sigma = np.double(input())
        if (sigma <= 0): raise ValueError("Unexpected value for sigma (should be a float > 0)")
        # f_r = F2
    print('%.3f' % rmse(f, f_r))